### ISSUE TITLE
Syntax Error when executing the dpg.py

### ISSUE THREAD

**Issue by ayasario** [sameera-madushan/Diceware-Password-Generator#2]
When I try to run the dpg.py file via the Linux command line, it gives me a syntax error "File "dpg.py", line 47
    print(i, end=' ')"
                     ^

Any idea how to solve this?
Thanks

**Comment by sameera-madushan** [comment]
Remove the single quotation mark ( " ) at the end. It should be as follow.
print(i, end=' ')
